source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def common
    pod 'Alamofire', '~> 4.0'
    pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'master'
    pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'master'
end

target 'RxAlamofire-iOS-Example' do
    #platform :ios, '9.0'
    common
end

target 'RxAlamofire-tvOS-Example' do
    #platform :tvos, '9.0'
    common
end

target 'RxAlamofire-iOS' do
   common
end

target 'RxAlamofireTests' do
    common
    pod 'OHHTTPStubs', '~> 5.0'
    pod 'OHHTTPStubs/Swift', '~> 5.0'
    pod 'RxBlocking', '~> 3.0.0-beta.2'
end

target 'RxAlamofire-tvOS' do
    common
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
