source "https://github.com/CocoaPods/Specs.git"

use_frameworks!
platform :ios, "9.0"

def common
  pod "Alamofire", "~> 4.8"
  pod "RxSwift", "~> 5.0"
  pod "RxCocoa", "~> 5.0"
end

target "RxAlamofire-iOS" do
  common
end

target "RxAlamofire-iOS-Example" do
  common
end

target "RxAlamofire-tvOS" do
  platform :tvos, "9.0"
  common
end

target "RxAlamofire-tvOS-Example" do
  platform :tvos, "9.0"
  common
end

target "RxAlamofire-watchOS" do
  platform :watchos, "3.0"
  common
end

target "RxAlamofire-macOS" do
  platform :osx, "10.10"
  common
end
