source "https://github.com/CocoaPods/Specs.git"

use_frameworks!

def common
  pod "Alamofire", "~> 4.8"
  pod "RxSwift", "~> 4.4"
  pod "RxCocoa", "~> 4.4"
end

target "RxAlamofire-iOS-Example" do
  platform :ios, "9.0"
  common
end

target "RxAlamofire-tvOS-Example" do
  platform :tvos, "9.0"
  common
end

target "RxAlamofire-iOS" do
  platform :ios, "9.0"
  common
end

target "RxAlamofireTests" do
  platform :ios, "9.0"
  common
  pod "OHHTTPStubs", "~> 7.0"
  pod "OHHTTPStubs/Swift", "~> 7.0"
  pod "RxBlocking", "~> 4.4"
end

target "RxAlamofire-tvOS" do
  platform :tvos, "9.0"
  common
end
