#if !canImport(ObjectiveC)
  import XCTest

  extension RxAlamofireSpec {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RxAlamofireSpec = [
      ("testBasicRequest", testBasicRequest),
      ("testDecodable", testDecodable),
      ("testDownloadResponse", testDownloadResponse),
      ("testDownloadResponseSerialized", testDownloadResponseSerialized),
      ("testInterceptorAdapt", testInterceptorAdapt),
      ("testInterceptorRetry", testInterceptorRetry),
      ("testJSONRequest", testJSONRequest),
      ("testRequestDecodable", testRequestDecodable),
      ("testRequestDecodableURLRequest", testRequestDecodableURLRequest),
      ("testRxProgress", testRxProgress),
      ("testStringRequest", testStringRequest)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(RxAlamofireSpec.__allTests__RxAlamofireSpec)
    ]
  }
#endif
