name: Deploy to Cocoapods

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Resolve dependencies
        run: |
          bundle

      # - name: Deploy to Cocoapods
      #   run: |
      #     set -eo pipefail
      #     export RELEASE_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
      #     pod lib lint --allow-warnings
      #     pod trunk push --allow-warnings
      #   env:
      #     COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
