name: Build pipeline

on:
  push:
    branches: 
      - 'feature/**'
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Resolve dependencies
        run: |
          brew bundle

      # - name: Danger
      #   run: |
      #     danger-swift ci
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore SPM Cache
        uses: actions/cache@v1
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and test (SPM)
        run: |
          swift build
          swift test

      - name: Generate Xcodeproj
        run: |
          xcodegen

      - name: Restore Carthage Cache
        uses: actions/cache@v1
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-

      - name: Resolving Carthage dependencies
        run: |
          carthage update --cache-builds --new-resolver --configuration Debug

      - name: Testing "RxAlamofire iOS" on Swift 5.1
        run: |
          xcodebuild test SWIFT_VERSION=5.1 -scheme 'RxAlamofire iOS' -project 'RxAlamofire.xcodeproj' -sdk iphonesimulator -destination "platform=iOS simulator,name=iPhone 11"

      - name: Testing "RxAlamofire tvOS" on Swift 5.1
        run: |
          xcodebuild test SWIFT_VERSION=5.1 -scheme 'RxAlamofire tvOS' -project 'RxAlamofire.xcodeproj' -destination "platform=tvOS simulator,name=Apple TV 4K"

      - name: Testing "RxAlamofire macOS" on Swift 5.1
        run: |
          xcodebuild test SWIFT_VERSION=5.1 -scheme 'RxAlamofire macOS' -project 'RxAlamofire.xcodeproj' 
